### PR TITLE
Reorganise repo and setup to deploy from gh-pages

### PR DESCRIPTION
**Pull request by EllaKaye**
This is a substantial pull request, which does the following:

- brings the website source to the root level
- sets up a GitHub Action (GHA) workflow to deploy from a gh-pages branch
    - **It will probably be necessary to run `quarto publish gh-pages` once locally to get this working in this repo**
- deletes the `docs` directory and removes the `_sites` directory
    - no longer need to render to `docs` as publishing through `gh-pages` instead
    - no longer need to have the `_sites` folder checked-in as the GHA takes care of building the site
- deletes the `archive` directory (have put this on a separate branch) 
- creates a listings page for the blog
 - puts each blog post in its own folder
     - folder name has format `YYYY-MM-DD_post-title-in-kebab-case`
     - post itself is always `index.qmd`
     - updates to yaml of each post to bring it in line with Quarto conventions
     - currently all images are in `images/blog/old-slug` but would be good at some point to move images for each post into its folder under `blog`

A preview of the site with these changes can be seen at <https://ellakaye.github.io/website_source>

### CODE REVIEW

**Comment by hturner** [comment]
Thanks Ella.

If we are going to change the URLs for the blog posts, I think it would be best to remove the date from the slug. One real pain was reviewing posts that a contributor or contributors wrote on one date and then remembering to update to the actual publishing date before publishing. Since the date will appear on the post, there's no real advantage having it in the slug - I'm sure we can always come up with a unique title! Hopefully then we can work purely with automatically generated dates and not have to do anything manual.

Still, I will merge for now as this PR is already large enough and at least we can get the new GH action working.

**Comment by PythonCoderUnicorn** [comment]
i did not see a reason to have such a long slug name for the url for each blog post, having it renamed to main title of post is one thing but the super long name is less than ideal but that's my opinion

**Comment by hturner** [comment]
With blogdown you used to be able to do 

```new_post("Title in Title Case", kind = "blog")```

and the kebab case slug would be automatically created for you. I'm not sure if you do something similar with Quarto.

**Comment by EllaKaye** [comment]
I agree with both of you. I did it this way to be as close as possible to the blogdown slug, but @hturner is right that we don't need the date in the slug @PythonCoderUnicorn is right that the text part doesn't need to be the full title. We're going to have to do a redirect in any case so it may as well be to something easier! I can make these changes but it probably won't be until Monday now.

**Pull request merged**
