### PR TITLE
LatAm BioC workshop.

### PR DESCRIPTION
**Pull request by areyesq89**
Added the paragraph with the description of the R/Bioconductor developers' workshop.

### CODE REVIEW

**Comment by hturner** [comment]
Is there a website for the workshop yet and/or could it be added to http://master.bioconductor.org/help/events/? Even if this is just a basic page with the information you have here, it would be helpful for people to know where to look for registration info etc when it becomes available. Also it would mean we don't need to have all the details of the instructors and organizing committee here, which is a bit much given we are covering several events and initiatives.

**Comment by areyesq89** [comment]
Unfortunately the website is not yet ready. Will mention this to the organizing committee (I think we really need one soon to start promoting the event).

**Comment by hturner** [comment]
Thanks, depending how speedy other contributors are the website maybe ready before we publish, but will merge this for now.

**Comment by hturner** [comment]
I've made a draft of the full post now. I haven't changed your section much, other than to put the location and date in the main text. Let me know if you have any comments, I plan to publish the post in the next few days.

**Pull request merged**
